version: "3.7"

services:
  backend:
    container_name: produtos-api
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=9000
    volumes:
      - ./src:/var/www/myapp/src
      - ./test:/var/www/myapp/test
    working_dir: /var/www/myapp
    ports:
      - "9001:9000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    networks:
      - myapp
  mysql: # Example Service
    container_name: myapp_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp
      - MYSQL_DATABASE=myapp_docker
    ports:
    - "3308:3306"
    volumes:
    - myapp_mysql_data:/var/lib/mysql
    networks:
      - myapp
  redis: # Example Service
    container_name: myapp_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - myapp_redis_data:/data
    networks:
      - myapp

volumes:
  myapp_mysql_data:
  myapp_redis_data:

networks:
  myapp:
    driver: bridge